k9s:
  refreshRate: 1
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: true
  crumbsless: false
  readOnly: false
  noIcons: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 60
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: kubernetes-admin@kubernetes
  currentCluster: kubernetes
  clusters:
    kind-kind:
      namespace:
        active: all
        favorites:
        - all
        - default
      view:
        active: po
      featureGates:
        nodeShell: true
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    kubernetes:
      namespace:
        active: yuanqijing
        favorites:
        - all
        - kube-system
        - yuanqijing
        - default
      view:
        active: pod
      featureGates:
        nodeShell: true
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /var/folders/5p/wydclj_55gjb45fkffsd8nd80000gn/T/k9s-screens-mac
